FROM golang:1.23 AS builder
RUN go version
WORKDIR /lambda

COPY ./src/go.mod ./src/go.sum ./
RUN go mod download
COPY ./src/. ./
RUN GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap .

FROM public.ecr.aws/lambda/provided:al2023 AS lambda-runtime
COPY --from=builder /lambda/bootstrap ${LAMBDA_TASK_ROOT}
ENTRYPOINT [ "./bootstrap" ]