name: apply/one
run-name: apply/one of ${{ inputs.application }} against ref ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      application:
        description: The application to interact with
        type: choice
        options:
          - webhook-lambda
          - api-gateway

jobs:
  apply:
    name: apply ${{inputs.application}}
    uses: ./.github/workflows/reusable/apply.yaml
    secrets: inherit
    permissions:
      contents: read
    with:
      application: ${{inputs.application}}
      tenv_version: ${{ vars.tenv_version }}
