name: apply/all
run-name: apply/all against ref ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  apply-webhook-lambda:
    uses: ./.github/workflows/reusable/apply.yaml
    secrets: inherit
    permissions:
      contents: read
    with:
      application: webhook-lambda
      tenv_version: ${{ vars.tenv_version }}

  apply-api-gateway:
    uses: ./.github/workflows/reusable/apply.yaml
    secrets: inherit
    permissions:
      contents: read
    with:
      application: api-gateway
      tenv_version: ${{ vars.tenv_version }}
