name: Terragrunt Plan (All)
run-name: plan/all against ref ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  plan-webhook-lambda:
    uses: ./.github/workflows/plan_reusable.yaml
    with: 
      application: webhook-lambda
  plan-api-gateway:
    uses: ./.github/workflows/plan_reusable.yaml
    secrets:
      WEHBOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    with: 
      application: api-gateway
          

  


