name: Terragrunt Plan (One)
run-name: plan/one of ${{ inputs.application }} against ref ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      application:
        description: The application to interact with
        type: choice
        options:
          - webhook-lambda
          - api-gateway

jobs:
  plan:
    name: Plan ${{inputs.application}}
    uses: ./.github/workflows/plan-reusable.yaml
    with: 
      application: ${{inputs.application}}
    secrets:
      WEHBOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      


