name: plan/all
run-name: plan/all against ref ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  plan-webhook-lambda:
    uses: ./.github/workflows/plan-reusable.yaml
    secrets: inherit
    permissions:
      contents: read
    with:
      application: webhook-lambda
      tenv_version: ${{ vars.tenv_version }}

  plan-api-gateway:
    uses: ./.github/workflows/plan-reusable.yaml
    secrets: inherit
    permissions:
      contents: read
    with:
      application: api-gateway
      tenv_version: ${{ vars.tenv_version }}
