name: Terragrunt Plan (All)
run-name: plan/all against ref ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  plan-webhook-lambda:
    uses: ./.github/workflows/plan-reusable.yaml
    permissions:
      contents: read
    with:
      application: webhook-lambda
      tenv_version: ${{ vars.tenv_version }}

  plan-api-gateway:
    uses: ./.github/workflows/plan-reusable.yaml
    permissions:
      contents: read
    secrets:
      WEHBOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    with:
      application: api-gateway
      tenv_version: ${{ vars.tenv_version }}
