on:
  workflow_call:
    inputs:
      application:
        description: The application to interact with
        required: true
        type: string
      tenv_version:
        description: The tenv version to use
        required: true
        type: string
    secrets:
      WEHBOOK_SECRET:
        description: "GitHub Webhook secret"
        required: false
      PAT_TOKEN:
        description: "Github PAT Token For Making Calls"
        required: false

jobs:
  plan-application:
    concurrency: tg-plan-${{ inputs.application }}
    runs-on: ubuntu-22.04
    env:
      TF_VAR_github_webhook_secret_string: ${{ secrets.WEHBOOK_SECRET }}
      TF_VAR_github_PAT_secret_string: ${{ secrets.PAT_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Plan ${{ inputs.application }}
        uses: ./.github/workflows/composite/plan
        with:
          application: ${{ inputs.application }}
          tenv_version: ${{ inputs.tenv_version }}
